import React,{useEffect,useRef,useState} from 'react';
import {BrainCircuit,Mic2,Upload,Download,Trash2,Play,Activity,ShieldAlert} from 'lucide-react';
const API=import.meta.env.VITE_API_URL||'http://localhost:3001';
const fmt=n=>n==null?'—':typeof n==='number'?n.toLocaleString('es-CL'):n;
export default function App(){
 const [records,setRecords]=useState(()=>{try{return JSON.parse(localStorage.getItem('psia_audio_records')||'[]')}catch{return[]}});const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');const input=useRef();
 useEffect(()=>localStorage.setItem('psia_audio_records',JSON.stringify(records)),[records]);
 async function analyzeFile(file){if(!file)return;setBusy(true);setMsg('Analizando audio…');try{const fd=new FormData();fd.append('audio',file);const r=await fetch(`${API}/api/audio/analyze`,{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error||'Error');const rec={id:crypto.randomUUID(),saved_at:new Date().toISOString(),...j};setRecords(x=>[rec,...x]);setMsg('Análisis guardado localmente.')}catch(e){setMsg(`Error: ${typeof e.message==='string'?e.message:JSON.stringify(e.message)}`)}finally{setBusy(false)}}
 async function sample(){setBusy(true);setMsg('Cargando audio base…');try{const r=await fetch(`${import.meta.env.BASE_URL}audio/audio_base.wav`);const b=await r.blob();await analyzeFile(new File([b],'audio_base.wav',{type:'audio/wav'}))}catch(e){setMsg('No se pudo cargar el audio base.');setBusy(false)}}
 function exportJson(){const payload={schema:'psia.export.v1',exported_at:new Date().toISOString(),record_count:records.length,records};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`psia_export_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
 function clear(){if(confirm('¿Eliminar los análisis guardados en este navegador?'))setRecords([])}
 const last=records[0];return <div className="appShell"><aside className="sidebar"><div className="brand"><div className="brandMark"><BrainCircuit size={24}/></div><div><b>PsiA</b><small>Audio Engine v0.3.0</small></div></div><nav><button className="active"><Activity size={18}/> Laboratorio de audio</button></nav><div className="privacy"><ShieldAlert size={18}/><div><b>Medición, no diagnóstico</b><span>La versión actual mide señal acústica y no infiere un estado clínico.</span></div></div></aside><main><header><div><p className="eyebrow">PROTOTIPO FUNCIONAL</p><h1>Análisis acústico local</h1><p className="sub">React → Node/Express → Python/librosa → almacenamiento local → JSON</p></div><button className="profile" onClick={exportJson} disabled={!records.length}><Download size={17}/> Exportar JSON</button></header>
 <section className="heroCard"><div><span className="statusPill">Python habilitado</span><h2>Prueba un audio y observa exactamente qué datos genera PsiA.</h2><p>El audio se envía al servicio local, Python calcula métricas acústicas y Node devuelve un JSON. El navegador conserva el resultado; el archivo de audio no se guarda en esta versión.</p><div className="heroActions"><button onClick={sample} disabled={busy}><Play size={17}/> Probar audio base</button><button className="secondary" onClick={()=>input.current.click()} disabled={busy}><Upload size={17}/> Subir mi audio</button><input ref={input} hidden type="file" accept="audio/*,.wav,.mp3,.m4a,.ogg" onChange={e=>analyzeFile(e.target.files?.[0])}/></div>{msg&&<p className="runMessage">{msg}</p>}</div><div className="heroGauge"><div className="ring"><span>{records.length}</span><small>análisis<br/>guardados</small></div><p>Persistencia: <b>localStorage</b></p></div></section>
 <div className="grid2"><section className="panel"><div className="panelTitle"><div><p className="eyebrow">ÚLTIMO RESULTADO</p><h3>Métricas acústicas</h3></div></div>{last?<div className="metricGrid">{[['Duración',last.source?.duration_sec,'s'],['Muestreo',last.source?.sample_rate_hz,'Hz'],['Pitch medio',last.acoustic?.pitch_hz_mean,'Hz'],['Variabilidad pitch',last.acoustic?.pitch_hz_std,'Hz'],['Energía RMS',last.acoustic?.rms_energy_mean,''],['Silencio estimado',last.acoustic?.estimated_silence_sec,'s'],['Ratio silencio',last.acoustic?.estimated_silence_ratio,''],['Centroide espectral',last.acoustic?.spectral_centroid_hz_mean,'Hz']].map(([a,b,c])=><div className="metric" key={a}><small>{a}</small><b>{fmt(b)} {c}</b></div>)}</div>:<div className="empty">Aún no hay análisis. Usa el audio base para generar el primero.</div>}</section>
 <section className="panel"><div className="panelTitle"><div><p className="eyebrow">DATOS GUARDADOS</p><h3>Registro JSON</h3></div></div><pre className="jsonPreview">{last?JSON.stringify(last,null,2):'{}'}</pre></section></div>
 <section className="panel historyPanel"><div className="panelTitle"><div><p className="eyebrow">HISTORIAL LOCAL</p><h3>Análisis realizados</h3></div><button className="iconText" onClick={clear} disabled={!records.length}><Trash2 size={16}/> Limpiar</button></div>{records.length?records.map(r=><div className="audioRow" key={r.id}><div><b>{r.source?.filename}</b><span>{new Date(r.saved_at).toLocaleString('es-CL')}</span></div><div><span>{r.source?.duration_sec}s</span><span>pitch {fmt(r.acoustic?.pitch_hz_mean)} Hz</span><span>silencio {fmt(r.acoustic?.estimated_silence_ratio)}</span></div></div>):<div className="empty">Sin registros.</div>}</section>
 </main></div>}
